apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: axelkjellin/pedido
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://techchallenge-rds.cpgtz5tfkqus.us-east-1.rds.amazonaws.com:3306/dbtechchallange"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: SPRING_PROFILES_ACTIVE
              value: prd
          command: ["dockerize", "-wait", "tcp://techchallenge-rds.cpgtz5tfkqus.us-east-1.rds.amazonaws.com:3306", "-timeout", "90s", "java", "-jar", "/workspace/app.jar"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
