apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA== # root
  mysql-database: ZGJ0ZWNoY2hhbGxhbmdl # dbtechchallange
  mysql-user: dHVybWFmaWFw # turmafiap
  mysql-password: UGFzc3dvcmQxMjM= # Password123
  jdbc-datasource-url: dGVjaGNoYWxsZW5nZS1yZHMuY3BndHo1dGZrcXVzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ== # techchallenge-rds.cpgtz5tfkqus.us-east-1.rds.amazonaws.com