apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: customer
          image: indigrinada/products-service:v1
          env:
            - name: SPRING_PROFILE
              value: placeholder
            - name: MYSQL_HOST
              value: ""
            - name: MYSQL_PORT
              value: ""
            - name: MYSQL_DATABSE
              value: ""
            - name: MYSQL_USER
              value: ""
            - name: MYSQL_PASSWORD
              value: ""
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer