apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: indigrinada/customer-service:latest
          env:
            - name: SPRING_PROFILE
              value: prd
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABSE
              value: dbtechchallenge
            - name: MYSQL_USER
              value: turmafiap
            - name: MYSQL_PASSWORD
              value: Password123
            - name: AWS_SQS_URL
              value: AWS_SQS_URL
            - name: AWS_REGION
              value: AWS_REGION
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-lb
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer