name: SonarCloud and Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run BDD tests
        run: mvn test -Dcucumber.options="--tags @bdd"

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=pedidos-techallenge_products-service
            -Dsonar.organization=pedidos-techallenge
            -Dsonar.host.url=https://sonarcloud.io
